FROM python:3.12-slim

WORKDIR /app

COPY requirements_fastapi.txt .
RUN pip install -r requirements_fastapi.txt

COPY source/tasks_app .

EXPOSE 8010

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010"]
